name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Build Tag Publish
      # You may pin to the exact commit or the version.
      # uses: bitovi/github-actions-docker-publish@def3cb9a3ef842b230bf575dc4f5e280ae6a6896
      uses: bitovi/github-actions-docker-publish@v1.0.7
      with:
        # Checkout the repository
        checkout: True
        # Tag to override default Logic
        use_sha: True
        # Docker org name.
        org_name: npghantasala
        # Name of the docker repository
        repo_name: test-actions-nginx
        # Tag default branch with latest tag instead of branch name.
        use_latest: False
        # Docker user
        docker_username: npghantasala
        # Docker password
        docker_password: Killerghan01$
