name: Docker Image CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      tag: npghantasala/test-actions-nginx:${{ GITHUB_REF_NAME }}
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: npghantasala
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
      uses: docker/build-push-action@v3.3.0
      with:
        # Do not use cache when building the image
        no-cache: True
        # Always attempt to pull all referenced images
        pull: True
        # Push is a shorthand for --output=type=registry
        push: True
        # List of tags
        tags: npghantasala/test-actions-nginx:${{ GITHUB_REF_NAME }}
        username: docker.io
