name: test
on: 
  push:
  workflow_dispatch:
    inputs:
      BUILD_IMAGES:
        type: boolean
        description: Build docker Images
        default: false
        required: true
env:
  VALUE : ''

jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "read file contents"
        if: ${{ github.event_name == 'push' && true || fromJSON(github.event.inputs.BUILD_IMAGES) }}
        run: |
             echo $(cat files/note.txt)
             echo "${{ github.event_name }}"
             
          
        
