name: Display commit message

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  VAR_NAME : ''
  VAR_VALUE : ''

jobs:
  pull-version:
    runs-on: ubuntu-latest
    steps:
    - name: pull commit message
      run: |
            commit_msg = ${{ github.event.head_commit.message }}
            echo "drdewewewq"

    
  
