name: test grep from commit message
on: 
  workflow_dispatch:
    inputs:
      VALUE:
        type: string
        default: 'demo'
        required: false
      LOAD_PROFILE:
        type: boolean
        description: LOAD_PROFILE
        default: false
        required: true
        
jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: "test message"
        run: |
              echo "${{ github.event.inputs.VALUE }}"
              echo "${{ github.event.inputs.LOAD_PROFILE }}"
              
      - uses: actions/checkout@v3
      
      - name: "read file contents"
        if: ${{ fromJSON(github.event.inputs.LOAD_PROFILE) }}
        run: |
             echo $(cat files/note.txt)
  job2:
    runs-on: ubuntu-latest
    needs:
    - pull-commit-message
    if: needs.pull-commit-message.result == 'failure'
    steps:
    - name: job2 echo
      run: echo "from job2"
          
        
