name: test
on: 
  push:
  workflow_dispatch:
env:
  VALUE : ''

jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "read file contents"
        run: |
             echo $(cat files/note.txt)
             echo "${{ github.event_name }}"
      - name: Geneate token for dev authentication
        run: |
             echo "dev_auth_token=$(echo -n `dd bs=512 if=/dev/urandom count=1 2>/dev/null | LC_ALL=C tr -dc "a-zA-Z0-9" | head -c 16`)"
             echo "dev_auth_token=$dev_auth_token">>$GITHUB_ENV
      - name: echo again
        run: echo $dev_auth_token
             
          
        
