name: test grep from commit message
on: 
  push:
  workflow_dispatch:
    inputs:
      VALUE:
        default: 'demo'
        required: false
        
env:
  VALUE : ${{ github.event.inputs.testvar }}

jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: "test message"
        run: |
              echo $VALUE
      - uses: actions/checkout@v3
      - name: "read file contents"
        run: |
             echo $(cat files/note.txt)
             
          
        
