name: test grep from commit message
on: 
  push
env:
  VALUE : ''

jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: "test pull commit message"
        run: |
              echo ${{ github.event.head_commit.message }}
              commit_msg="${{ github.event.head_commit.message }}"
              VALUE=$(echo $commit_msg|grep -o '\b\w*[0-9.]\w*\b')
        
