name: test grep from commit message
on: 
  push:
  workflow_dispatch:
    inputs:
      VALUE:
        type: string
        default: 'demo'
        required: false
      LOAD_PROFILE:
        type: boolean
        description: select if needed
        default: false
        required: true
        
jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: "test message"
        run: |
              echo "${{ github.event.inputs.VALUE }}"
      - uses: actions/checkout@v3
      - name: "read file contents"
        if: ${{ github.event.inputs.LOAD_PROFILE }}
        run: |
             echo $(cat files/note.txt)
             
          
        
