name: test grep from commit message
on: 
  push:
  workflow_dispatch:
    inputs:
      VALUE:
        type: string
        default: '[demo]'
        required: false
        
jobs:
  pull-commit-message:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        VALUE: ${{ fromJson(github.event.inputs.VALUE) }}
    steps:
      - name: "test message"
        run: |
              echo "${{ github.event.inputs.VALUE }}"
      - uses: actions/checkout@v3
        with:
          matrix-value: ${{ matrix.VALUE }}
      - name: "read file contents"
        run: |
             echo $(cat files/note.txt)
             
          
        
