name: Extract Variable from Commit Message

on:
  push:
    branches:
      - main

env:
  VAR_NAME: ''

jobs:
  extract-variable:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Commit Message
      run: |
        COMMIT_MESSAGE=$(git log -1 HEAD --pretty=format:%B)
        echo "Commit Message: $COMMIT_MESSAGE"

    - name: Extract Variable
      run: |
        VAR_VALUE=$(echo $COMMIT_MESSAGE | grep -oP "(?<=$VAR_NAME: )\w+")
        echo "Variable $VAR_NAME: $VAR_VALUE"
        echo "::set-env name=$VAR_NAME::$VAR_VALUE"
